### PR TITLE
Documentation minor update

### PR DESCRIPTION
**Pull request by it-praktyk**

### CODE REVIEW

**Comment by jborean93** [comment]
Thanks for the PR, are you just able to make the link changes to the base `README.md`. The rest of the changes seem to be cosmetic code formatting that don't make a difference to the final output and are really just a preference.

**Comment by it-praktyk** [comment]
> The rest of the changes seem to be cosmetic code formatting [...] are really just a preference.

Yes, it's (partially) true.

I just opened markdown files using Visual Studio Code with the plugin [markownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) installed and made proposed changes like
- [MD022 - Headers should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.7.0/doc/Rules.md#md022)
- [MD007 - Unordered list indentation](https://github.com/DavidAnson/markdownlint/blob/v0.7.0/doc/Rules.md#md007---unordered-list-indentation)

**Comment by jborean93** [comment]
Those particular rules seem to be rules that may or may not have issues with specific markdown parsers and not part of the actual Markdown spec. In this case a set of rules defined by a particular tool (that isn't installed by default) whereas there may be other tools that disagree with it.

I prefer to keep the formatting as is for a few reasons;

* Cosmetic PRs make it hard to attribute text/code with a certain user if another has just changed the formatting
* There are no linting tests run on a commit to enforce this structure and I probably won't enforce it manually in the future
* GH parser has no issue with the current structure

**Comment by it-praktyk** [comment]
OK, it's your choice.

**Pull request closed without merging**
